# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProductById = channel.unary_unary(
                '/inventory.InventoryService/GetProductById',
                request_serializer=inventory__pb2.GetProductByIdRequest.SerializeToString,
                response_deserializer=inventory__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.GetProductBySku = channel.unary_unary(
                '/inventory.InventoryService/GetProductBySku',
                request_serializer=inventory__pb2.GetProductBySkuRequest.SerializeToString,
                response_deserializer=inventory__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_unary(
                '/inventory.InventoryService/ListProducts',
                request_serializer=inventory__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=inventory__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/inventory.InventoryService/CreateProduct',
                request_serializer=inventory__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=inventory__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/inventory.InventoryService/UpdateProduct',
                request_serializer=inventory__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=inventory__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.DeactivateProduct = channel.unary_unary(
                '/inventory.InventoryService/DeactivateProduct',
                request_serializer=inventory__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=inventory__pb2.DeleteProductResponse.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/inventory.InventoryService/DeleteProduct',
                request_serializer=inventory__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=inventory__pb2.DeleteProductResponse.FromString,
                _registered_method=True)
        self.AdjustStock = channel.unary_unary(
                '/inventory.InventoryService/AdjustStock',
                request_serializer=inventory__pb2.AdjustStockRequest.SerializeToString,
                response_deserializer=inventory__pb2.StockResponse.FromString,
                _registered_method=True)
        self.GetStockLevel = channel.unary_unary(
                '/inventory.InventoryService/GetStockLevel',
                request_serializer=inventory__pb2.GetProductByIdRequest.SerializeToString,
                response_deserializer=inventory__pb2.StockResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProductById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductBySku(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdjustStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProductById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductById,
                    request_deserializer=inventory__pb2.GetProductByIdRequest.FromString,
                    response_serializer=inventory__pb2.ProductResponse.SerializeToString,
            ),
            'GetProductBySku': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductBySku,
                    request_deserializer=inventory__pb2.GetProductBySkuRequest.FromString,
                    response_serializer=inventory__pb2.ProductResponse.SerializeToString,
            ),
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=inventory__pb2.ListProductsRequest.FromString,
                    response_serializer=inventory__pb2.ListProductsResponse.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=inventory__pb2.CreateProductRequest.FromString,
                    response_serializer=inventory__pb2.ProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=inventory__pb2.UpdateProductRequest.FromString,
                    response_serializer=inventory__pb2.ProductResponse.SerializeToString,
            ),
            'DeactivateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateProduct,
                    request_deserializer=inventory__pb2.DeleteProductRequest.FromString,
                    response_serializer=inventory__pb2.DeleteProductResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=inventory__pb2.DeleteProductRequest.FromString,
                    response_serializer=inventory__pb2.DeleteProductResponse.SerializeToString,
            ),
            'AdjustStock': grpc.unary_unary_rpc_method_handler(
                    servicer.AdjustStock,
                    request_deserializer=inventory__pb2.AdjustStockRequest.FromString,
                    response_serializer=inventory__pb2.StockResponse.SerializeToString,
            ),
            'GetStockLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockLevel,
                    request_deserializer=inventory__pb2.GetProductByIdRequest.FromString,
                    response_serializer=inventory__pb2.StockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProductById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetProductById',
            inventory__pb2.GetProductByIdRequest.SerializeToString,
            inventory__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductBySku(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetProductBySku',
            inventory__pb2.GetProductBySkuRequest.SerializeToString,
            inventory__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/ListProducts',
            inventory__pb2.ListProductsRequest.SerializeToString,
            inventory__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/CreateProduct',
            inventory__pb2.CreateProductRequest.SerializeToString,
            inventory__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/UpdateProduct',
            inventory__pb2.UpdateProductRequest.SerializeToString,
            inventory__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/DeactivateProduct',
            inventory__pb2.DeleteProductRequest.SerializeToString,
            inventory__pb2.DeleteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/DeleteProduct',
            inventory__pb2.DeleteProductRequest.SerializeToString,
            inventory__pb2.DeleteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdjustStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/AdjustStock',
            inventory__pb2.AdjustStockRequest.SerializeToString,
            inventory__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetStockLevel',
            inventory__pb2.GetProductByIdRequest.SerializeToString,
            inventory__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
