version: '3.9'

services:
  user_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - user_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  user:
    build:
      context: ../..
      dockerfile: services/user/Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      user_db:
        condition: service_healthy
    environment:
      DB_HOST: user_db
      DB: ${DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

volumes:
  user_db_data:
