# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"h\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"%\n\x12GetUserByIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\"&\n\x15GetUserByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"I\n\x11ModifyUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12#\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x15.user.RegisterRequest\"(\n\x15\x44\x65\x61\x63tivateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\"\x9c\x01\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\x08\x12\x12\n\ncreated_at\x18\x07 \x01(\t\x12\x12\n\nupdated_at\x18\x08 \x01(\t\"@\n\rLoginResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.user.UserResponse\x12\r\n\x05token\x18\x02 \x01(\t\"\"\n\x0fSuccessResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb5\x03\n\x0bUserService\x12\x35\n\x08Register\x12\x15.user.RegisterRequest\x1a\x12.user.UserResponse\x12\x30\n\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12;\n\x0bGetUserById\x12\x18.user.GetUserByIdRequest\x1a\x12.user.UserResponse\x12\x41\n\x0eGetUserByEmail\x12\x1b.user.GetUserByEmailRequest\x1a\x12.user.UserResponse\x12\x39\n\nModifyUser\x12\x17.user.ModifyUserRequest\x1a\x12.user.UserResponse\x12\x44\n\x0e\x44\x65\x61\x63tivateUser\x12\x1b.user.DeactivateUserRequest\x1a\x15.user.SuccessResponse\x12<\n\nDeleteUser\x12\x17.user.DeleteUserRequest\x1a\x15.user.SuccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=20
  _globals['_REGISTERREQUEST']._serialized_end=124
  _globals['_LOGINREQUEST']._serialized_start=126
  _globals['_LOGINREQUEST']._serialized_end=173
  _globals['_GETUSERBYIDREQUEST']._serialized_start=175
  _globals['_GETUSERBYIDREQUEST']._serialized_end=212
  _globals['_GETUSERBYEMAILREQUEST']._serialized_start=214
  _globals['_GETUSERBYEMAILREQUEST']._serialized_end=252
  _globals['_MODIFYUSERREQUEST']._serialized_start=254
  _globals['_MODIFYUSERREQUEST']._serialized_end=327
  _globals['_DEACTIVATEUSERREQUEST']._serialized_start=329
  _globals['_DEACTIVATEUSERREQUEST']._serialized_end=369
  _globals['_DELETEUSERREQUEST']._serialized_start=371
  _globals['_DELETEUSERREQUEST']._serialized_end=407
  _globals['_USERRESPONSE']._serialized_start=410
  _globals['_USERRESPONSE']._serialized_end=566
  _globals['_LOGINRESPONSE']._serialized_start=568
  _globals['_LOGINRESPONSE']._serialized_end=632
  _globals['_SUCCESSRESPONSE']._serialized_start=634
  _globals['_SUCCESSRESPONSE']._serialized_end=668
  _globals['_USERSERVICE']._serialized_start=671
  _globals['_USERSERVICE']._serialized_end=1108
# @@protoc_insertion_point(module_scope)
